language: php

sudo: false

install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - wget -O bin/composer.phar https://getcomposer.org/composer.phar
  - php -dmemory_limit=1G bin/composer.phar update
  - npm install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script: echo "memory_limit=1000M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: phpunit -c app/