language: php

sudo: false

services:
  - mysql

install:
  - mysql -e 'create database symfony;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - wget https://getcomposer.org/composer.phar
  - php -dmemory_limit=2G composer.phar update --dev --no-interaction
  - npm install
  - php app/console doctrine:schema:create --env=test

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

script: phpunit -c app/