services:

    user.login_success_handler:
        class: UserBundle\Handler\LoginSuccessHandler
        arguments:
            - @router
            - @security.token_storage
            - @session
        tags:
            - { name: 'monolog.logger', channel: 'security' }
